version: "3.8"

services:
  server:
    build:
      context: .
      args:
        - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - ichgram_network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ichgram_network
    restart: unless-stopped

networks:
  ichgram_network:
    driver: bridge

volumes:
  mongodb_data:
