version: '3.8'

services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - ichgram_network

networks:
  ichgram_network:
    driver: bridge

